In [1]:
import pandas as pd
import numpy as np

In [2]:
# 수요지 : 노인시설, 노인복지시설, 경로당, 버스정류장
# 후보지 : 공원, 실외운동기구, 야외휴게쉼터, 무더위쉼터

# 1. 데이터 로드

In [3]:
입지후보지 = pd.read_csv('입지후보지.csv')
print(입지후보지.shape)
입지후보지.head(2)

(376, 6)

       이름         위도          경도                    주소  분류  행정동
0  신부문화공원  36.818066  127.156156  충남 천안시 동남구 신부동 460-4  공원  신안동
1  청수호수공원  36.787191  127.149901    충남 천안시 동남구 청수동 270  공원  청룡동

In [4]:
노인인구 = pd.read_csv('읍면동별 고령자 인구.csv')
노인인구.head()

   지역명  노인 인구수
0  목천읍    4976
1  풍세면    2067
2  광덕면    1735
3   북면    1648
4  성남면    1283

In [5]:
노인시설 = pd.read_csv('노인시설.csv')
노인시설.head()

,시설구분,시설명,주소,경도,위도,행정동
0,경로식당,(사)대한노인회천안시지회,천안시 동남구 중앙로 217(신부동),127.152538,36.817721,신안동
1,노인요양시설,드림요양원,천안시 서북구 성환읍 무내3길 15,127.151399,36.947174,성환읍
2,노인요양시설,북천안요양원,천안시 서북구 성환읍 성월수향길 30,127.137400,36.921172,성환읍
3,재가노인복지시설 주야간보호,북천안요양원부설주야간보호센터,천안시 서북구 성환읍 성월수향길 30,127.137400,36.921172,성환읍
4,노인요양공동생활가정,비타민2요양원,"천안시 서북구 성환읍 성환9길 9, 2층",127.129025,36.916203,성환읍

In [6]:
노인복지시설 = pd.read_csv('노인복지시설.csv')
노인복지시설.head()

,구분,시군,기능,이름,주소,경도,위도,행정동
0,노인의료복지시설,천안시,노인요양시설(개정법),행복나눔노인요양원,천안시 동남구 태조산길 266(유량동),127.188457,36.820410,청룡동
1,노인의료복지시설,천안시,노인요양시설(개정법),천안노인전문요양원,천안시 동남구 정골2길 97(구성동),127.177258,36.799774,청룡동
2,노인의료복지시설,천안시,노인요양시설(개정법),천안삼거리요양원,천안시 동남구 샛골길 1-15(삼룡동),127.168367,36.786721,청룡동
3,노인의료복지시설,천안시,노인요양시설(개정법),천안실버안요양원,천안시 동남구 천안대로 215 3층(삼룡동),127.165077,36.767388,청룡동
4,노인의료복지시설,천안시,노인요양시설(개정법),천안제일요양원,천안시 동남구 광풍로 1828(청당동),127.145704,36.781379,청룡동

In [7]:
경로당 = pd.read_csv('경로당.csv')
경로당.head()

          경로당명               주소  회원수  행정동          경도         위도
0      구룡1통경로당   천안시 동남구 용평1길35   54  청룡동  127.155223  36.764018
1      구룡3통경로당  천안시 동남구 중리1길144   36  청룡동  127.148923  36.766644
2     청룡14통경로당    천안시 동남구 대흥로38   27  청룡동  127.157148  36.797130
3  구성5통굴울마을경로당   천안시 동남구 정골1길82   30  청룡동  127.173356  36.792231
4        구광경로당  천안시 동남구 삼룡천2길53   27  청룡동  127.161178  36.795539

In [8]:
버스정류장 = pd.read_csv('버스정류장.csv')
버스정류장.head()

          정류장번호     정류장명         X좌표        Y좌표  행정동
0  CAB285001036   충무로사거리  127.160631  36.798626  청룡동
1  CAB285001043    신안25통  127.185896  36.830897  신안동
2  CAB285001044    신안25통  127.185512  36.830863  신안동
3  CAB285001045      각원사  127.189222  36.833073  신안동
4  CAB285001046  호서대(천안)  127.179728  36.830391  신안동

In [9]:
공원 = pd.read_csv('공원.csv')
공원.head()

,이름,주소,도로명주소,위도,경도,category,주소_정제
0,신부문화공원,충남 천안시 동남구 신부동 460-4,NaN,36.818066,127.156156,여행 > 공원,충남 천안시 동남구 신부동
1,청수호수공원,충남 천안시 동남구 청수동 270,충남 천안시 동남구 청수로 20,36.787191,127.149901,여행 > 공원 > 도시근린공원,충남 천안시 동남구 청수동
2,구성1공원,충남 천안시 동남구 구성동 435-1,NaN,36.797602,127.162168,여행 > 공원,충남 천안시 동남구 구성동
3,천안삼거리공원 (2025년 9월 예정),충남 천안시 동남구 삼룡동 299-1,충남 천안시 동남구 충절로 410,36.783025,127.168404,여행 > 공원,충남 천안시 동남구 삼룡동
4,청수산림공원,충남 천안시 동남구 청수동 산 5-3,충남 천안시 동남구 풍세로 924-2,36.791373,127.151665,여행 > 공원 > 도시근린공원,충남 천안시 동남구 청수동

In [10]:
실외운동기구 = pd.read_csv('실외운동기구.csv')
실외운동기구.head()

,시설명,소재지,설치년도,운동기구1,운동기구1 개수,운동기구2,운동기구2 개수,운동기구3,운동기구3 개수,운동기구4,운동기구4 개수,운동기구5,운동기구5 개수,운동기구6,운동기구6 개수,운동기구7,운동기구7 개수,경도,위도,소재지_짧음
0,하천변,청룡동 삼룡천2길 67,2015,공중걷기,1,파도타기,1.0,허리돌리기+등허리지압기,1.0,상체근육풀기,1.0,윗몸일으키기,1.0,0,0.0,0,0.0,127.160499,36.796602,청룡동
1,노인회관,신안동 단대로 161-12,2016,허리돌리기,1,달리기,1.0,역기올리기,1.0,래그프래스,1.0,어깨근육풀기,1.0,0,0.0,0,0.0,127.167552,36.829085,신안동
2,마을공터,신안동 단대로 91-4,2021,하늘걷기+허리돌리기,1,싸이클링+오금펴기,1.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,127.160785,36.830025,신안동
3,마을회관,성환읍 무내1길 27,2015,허리돌리기+등러리지압기,1,파도타기+오금펴기,1.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,127.152083,36.945450,성환읍
4,마을회관,성환읍 도야길 29,2015,허리돌리기+등러리지압기,1,윗몸일으키기+등러리근육풀기,1.0,파도타기+오금펴기,1.0,0,0.0,0,0.0,0,0.0,0,0.0,127.163574,36.946267,성환읍

In [11]:
야외휴게쉼터 = pd.read_csv('야외휴게쉼터.csv')
야외휴게쉼터.head()

,설치주소,설치위치,설치년도,설치형상,관리부서,경도,위도,구,설치주소_짧음
0,충청남도 천안시 동남구 구성동 435-1,구성1공원,2015.0,정자(1개),정원녹지과(도시숲조성팀),127.162267,36.797611,동남구,충청남도 천안시 동남구 구성동
1,충청남도 천안시 동남구 신부동 124 일원,도솔광장,2017.0,정자(1개),정원녹지과(도시숲조성팀),127.161532,36.824539,동남구,충청남도 천안시 동남구 신부동
2,충청남도 천안시 동남구 신부동 124 일원,도솔광장,2017.0,파고라(9개),정원녹지과(도시숲조성팀),127.161532,36.824539,동남구,충청남도 천안시 동남구 신부동
3,충청남도 천안시 서북구 성환읍 성환리 406,창환주택 단지 안,2009.0,육각정자,정원녹지과(녹지관리팀),127.132731,36.912918,서북구,충청남도 천안시 서북구 성환읍
4,충청남도 천안시 서북구 성환읍 신방리 293-12,신방2리경로당,2010.0,사각정자,정원녹지과(녹지관리팀),127.079563,36.941607,서북구,충청남도 천안시 서북구 성환읍

In [12]:
무더위쉼터 = pd.read_csv('무더위쉼터.csv')
무더위쉼터.head()

,시군구명,읍면동명,Unnamed: 2,연도,Unnamed: 4,쉼터명칭,상세주소,사용여부,시설면적,이용가능인원수,소재지지번주소,경도,위도,시설유형명
0,천안시 동남구 청룡동,동남구 청룡동,NaN,2024,NaN,부영사랑으로 경로당,충청남도 천안시 동남구 청수8로 72,Y,110,27,충청남도 천안시 동남구 청수8로 72,127.159697,36.788948,노인시설
1,천안시 동남구 청룡동,동남구 청룡동,NaN,2024,NaN,꿈에그린 경로당,충청남도 천안시 동남구 청수14로 13,Y,80,20,충청남도 천안시 동남구 청수14로 13,127.147496,36.785860,노인시설
2,천안시 동남구 청룡동,동남구 청룡동,NaN,2024,NaN,청룡동 주민센터,충청남도 천안시 동남구 청수14로 99,Y,50,12,충청남도 천안시 동남구 청수14로 99,127.156783,36.786016,주민센터
3,천안시 동남구 청룡동,동남구 청룡동,NaN,2024,NaN,한양수자인블루시티(아),충청남도 천안시 동남구 청당4로 60,Y,125,22,충청남도 천안시 동남구 청당4로 60,127.151035,36.778069,노인시설
4,천안시 동남구 청룡동,동남구 청룡동,NaN,2024,NaN,행정타운 두산위브(아) 경로당,충청남도 천안시 동남구 청당3길 147,Y,146,20,충청남도 천안시 동남구 청당3길 147,127.161171,36.779101,노인시설

In [13]:
버스이용량 = pd.read_csv('시간대별 시내버스 이용량.csv')
버스이용량.head()

           날짜    10    11    12     13    14     15     16
0  2024-07-01  6623  6842  8598   9192  7476   8807  11628
1  2024-07-02  4489  4734  7836   9328  6556   7767   9833
2  2024-07-03  6235  6351  9260  10318  8158   9822  10277
3  2024-07-04  6369  6400  8765   9710  7522   8769  11506
4  2024-07-05  6457  6595  9202   9417  7930  11333  11736

# 2. 행정동별 데이터 분리

In [14]:
청룡동_버스정류장 = 버스정류장[버스정류장['행정동']=='청룡동']
청룡동_버스정류장.to_csv("청룡동_버스정류장.csv", index=False, encoding='utf-8-sig')

신안동_버스정류장 = 버스정류장[버스정류장['행정동']=='신안동']
신안동_버스정류장.to_csv("신안동_버스정류장.csv", index=False, encoding='utf-8-sig')

성환읍_버스정류장 = 버스정류장[버스정류장['행정동']=='성환읍']
성환읍_버스정류장.to_csv("성환읍_버스정류장.csv", index=False, encoding='utf-8-sig')

In [15]:
청룡동_경로당 = 경로당[경로당['행정동']=='청룡동']
청룡동_경로당.to_csv("청룡동_경로당.csv", index=False, encoding='utf-8-sig')

신안동_경로당 = 경로당[경로당['행정동']=='신안동']
신안동_경로당.to_csv("신안동_경로당.csv", index=False, encoding='utf-8-sig')

성환읍_경로당 = 경로당[경로당['행정동']=='성환읍']
성환읍_경로당.to_csv("성환읍_경로당.csv", index=False, encoding='utf-8-sig')

In [16]:
청룡동_노인복지시설 = 노인복지시설[노인복지시설['행정동']=='청룡동']
청룡동_노인복지시설.to_csv("청룡동_노인복지시설.csv", index=False, encoding='utf-8-sig')

신안동_노인복지시설 = 노인복지시설[노인복지시설['행정동']=='신안동']
신안동_노인복지시설.to_csv("신안동_노인복지시설.csv", index=False, encoding='utf-8-sig')

성환읍_노인복지시설 = 노인복지시설[노인복지시설['행정동']=='성환읍']
성환읍_노인복지시설.to_csv("성환읍_노인복지시설.csv", index=False, encoding='utf-8-sig')

In [17]:
청룡동_노인시설 = 노인시설[노인시설['행정동']=='청룡동']
청룡동_노인시설.to_csv("청룡동_노인시설.csv", index=False, encoding='utf-8-sig')

신안동_노인시설 = 노인시설[노인시설['행정동']=='신안동']
신안동_노인시설.to_csv("신안동_노인시설.csv", index=False, encoding='utf-8-sig')

성환읍_노인시설 = 노인시설[노인시설['행정동']=='성환읍']
성환읍_노인시설.to_csv("성환읍_노인시설.csv", index=False, encoding='utf-8-sig')

# 3. 수요 지점 좌표 리스트 생성

In [18]:
노인시설_points = np.array([list(i) for i in zip(노인시설['위도'], 노인시설['경도'])])
print(노인시설_points.shape)
노인시설_points[:2]

(23, 2)

array([[ 36.81772127, 127.1525376 ],
       [ 36.94717367, 127.1513989 ]])

In [19]:
노인복지시설_points = np.array([list(i) for i in zip(노인복지시설['위도'], 노인복지시설['경도'])])
print(노인복지시설_points.shape)
노인복지시설_points[:2]

(16, 2)

array([[ 36.82041018, 127.1884568 ],
       [ 36.79977396, 127.177258  ]])

In [20]:
버스_points = np.array([list(i) for i in zip(버스정류장['Y좌표'], 버스정류장['X좌표'])])
print(버스_points.shape)
버스_points[:2]

(341, 2)

array([[ 36.79862631, 127.1606308 ],
       [ 36.83089653, 127.1858961 ]])