In [1]:
import pandas as pd
df = pd.read_csv("입지후보지.csv")

df1 = pd.read_csv("성환읍_후보지(MCLP).csv")
df2 = pd.read_csv("성환읍_후보지(P-median).csv")

# 공통 컬럼 기준 교집합 merge
merged = pd.merge(df1, df2, on="주소", how="inner")

# 중복 제거
merged1 = merged.drop_duplicates()
merged1.drop(['위도_y', '경도_y', '이름_y'], axis=1, inplace=True)
merged1['행정동'] = '성환읍'
merged1

    이름_x       위도_x        경도_x            주소  행정동
0  아파트단지  36.902747  127.109374  성환읍 율금1길 276  성환읍

In [2]:
df1 = pd.read_csv("청룡동_후보지(MCLP).csv")
df2 = pd.read_csv("청룡동_후보지(P-median).csv")

# 공통 컬럼 기준 교집합 merge
merged = pd.merge(df1, df2, on="주소", how="inner")

# 중복 제거
merged2 = merged.drop_duplicates()
merged2.drop(['위도_y', '경도_y', '이름_y'], axis=1, inplace=True)
merged2['행정동'] = '청룡동'
merged2

       이름_x       위도_x        경도_x                           주소  행정동
0  청당코오롱하늘채  36.779600  127.145900  충청남도 천안시 동남구 광풍로 1799 (청당동)  청룡동
1       하천변  36.796602  127.160499                 청룡동 삼룡천2길 67  청룡동

In [3]:
df1 = pd.read_csv("신안동_후보지(MCLP).csv")
df2 = pd.read_csv("신안동_후보지(P-median).csv")

# 공통 컬럼 기준 교집합 merge
merged = pd.merge(df1, df2, on="이름", how="inner")

# 중복 제거
merged3 = merged.drop_duplicates()
merged3.drop(['위도_y', '경도_y', '주소_y'], axis=1, inplace=True)
merged3.columns = ['이름_x', '위도_x', '경도_x', '주소']
merged3['행정동'] = '신안동'
merged3

       이름_x       위도_x        경도_x                        주소  행정동
0    신부문화공원  36.818066  127.156156      충남 천안시 동남구 신부동 460-4  신안동
1     신부6공원  36.823675  127.155425      충청남도 천안시 동남구 신부동 542  신안동
2     신부6공원  36.823675  127.155425      충청남도 천안시 동남구 신부동 542  신안동
3  안서3어린이공원  36.828279  127.185688    충청남도 천안시 동남구 안서동 270-5  신안동
4     안서1공원  36.840201  127.179318  충청남도 천안시 동남구 안서동 526-153  신안동

In [4]:
result = pd.concat([merged1, merged2, merged3]).reset_index(drop=True)
result.columns = ['이름', '위도', '경도', '주소', '행정동']

In [5]:
result.to_csv("최종후보지.csv", index=False, encoding="utf-8-sig")